//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityDemoClient.ClientProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientProxy.SecurityService")]
    public interface SecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecurityService/SayingHello", ReplyAction="http://tempuri.org/SecurityService/SayingHelloResponse")]
        string SayingHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecurityService/SayingHello", ReplyAction="http://tempuri.org/SecurityService/SayingHelloResponse")]
        System.Threading.Tasks.Task<string> SayingHelloAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityServiceChannel : SecurityDemoClient.ClientProxy.SecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<SecurityDemoClient.ClientProxy.SecurityService>, SecurityDemoClient.ClientProxy.SecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayingHello(string name) {
            return base.Channel.SayingHello(name);
        }
        
        public System.Threading.Tasks.Task<string> SayingHelloAsync(string name) {
            return base.Channel.SayingHelloAsync(name);
        }
    }
}
